### ISSUE TITLE
MESOS_NATIVE_JAVA_LIBRARY is not set

### ISSUE THREAD

**Issue by ankurcha** [mdsol/marathon_cookbook#28]
The current cookbook doesn't seem to correctly set the value of `MESOS_NATIVE_JAVA_LIBRARY` as per docs: https://mesosphere.github.io/marathon/docs/

**Comment by tomwganem** [comment]
+1

**Comment by tomwganem** [comment]
Actually, I think the main problem is https://github.com/mdsol/marathon_cookbook/blob/develop/recipes/default.rb#L28

I'm using this in conjunction with the mesos cookbook. '/usr/local/lib/libmesos.so' does not exist for me.

**Comment by tomwganem** [comment]
Sorry. That's wrong. It exists. But it points to '../../lib/libmesos.so'

**Comment by avinashkolluru** [comment]
+1
I'm using this in conjunction with mesos cookbook(version 0.23.0) by overriding the node['mesos']['version'] attribute which installs the .so file appended with the version
```
/usr/local/lib/libmesos-0.23.0.so
```
As a hack I had to copy the entire recipe and change the symlink
```
link '/usr/lib/libmesos.so' do
  to "/usr/local/lib/libmesos-#{node['mesos']['version']}.so"
end
```

**Comment by DarkGigaByte** [comment]
+1

**Comment by rveznaver** [comment]
Hi, this cookbook has a major release since this issue. Anyone still experiencing it with the latest master?

**Comment by caussourd** [comment]
@rveznaver Not experiencing this issue with the latest master.

**Comment by rveznaver** [comment]
Closing this issue as it seems to be resolved.

**Comment by crystalfuns** [comment]
Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Failed to load native Mesos library from /usr/local/lib/libmesos.so
java.lang.UnsatisfiedLinkError: Can't load library: /usr/local/lib/libmesos.so
  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
  at java.lang.Runtime.load0(Runtime.java:809)
  at java.lang.System.load(System.java:1086)
MESOS_NATIVE_JAVA_LIBRARY='/usr/local/lib/libmesos.so'
SPARK_EXECUTOR_URI=http://apache.claz.org/spark/spark-2.1.0/spark-2.1.0-bin-hadoop2.7.tgz

[11:49]  
I am running from my client (outside the mesos cluster). Do i need to install these libraries ?
