### ISSUE TITLE
Same zookeeper path used for both --master and --ha options

### ISSUE THREAD

**Issue by avinashkolluru** [mdsol/marathon_cookbook#30]
Currently the same zookeeper path(node['marathon']['zookeeper_path']) is used for both --master and -ha option when we set the node['marathon']['zookeeper_server_list'] attribute.
There should be support for different paths as per the documentation in https://mesosphere.github.io/marathon/docs/high-availability.html

**Comment by rveznaver** [comment]
```node['marathon']['zookeeper_path']``` has been removed and you are required to set up the full flag. Should work now!
