### ISSUE TITLE
LIBPROCESS_IP not being set on centos 7 node

### ISSUE THREAD

**Issue by avinashkolluru** [mdsol/marathon_cookbook#31]
The following command used in templates/default/sv-marathon-run.erb doesnt work on machine running centos
```
ip=$(ifconfig | grep inet | grep -v inet6 | grep -v '127.0.0.1' | awk -F: '{ print $2 }' | awk '{ print $1 }')
```
The output of "ifconfig | grep inet | grep -v inet6 | grep -v '127.0.0.1' " on my machine is
```
        inet x.x.x.x  netmask 255.255.0.0  broadcast 0.0.0.0
        inet y.y.y.y  netmask 255.255.240.0  broadcast a.b.c.d
```

**Comment by rveznaver** [comment]
The runit template has been removed. Please try with the latest master, it should work now using upstart. Thanks!
