### ISSUE TITLE
Please update default branch to master

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/marathon_cookbook#39]
Hey @harryw can you change the default branch back to master as we will be switching to a standard single (master) branch chef workflow for publishing changes to this cookbook.  Thanks!

**Comment by harryw** [comment]
Done.

**Comment by harryw** [comment]
Also: Merry Christmas!

**Comment by rayrod2030** [comment]
Thanks Harry!  Merry Christmas to you and your family as well! :santa:
