### ISSUE TITLE
Java 1.8 installation issue

### ISSUE THREAD

**Issue by caussourd** [mdsol/marathon_cookbook#41]
I got this error during the install:
```
* apt_package[openjdk-8-jdk] action install
    * No candidate version available for openjdk-8-jdk
    ================================================================================
    Error executing action `install` on resource 'apt_package[openjdk-8-jdk]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No candidate version available for openjdk-8-jdk
```

It seems that the java cookbook supports version 8 with Oracle only: https://supermarket.chef.io/cookbooks/java

I fixed the issue by adding the attributes: 
```
node['java']['install_flavor'] = 'oracle'
node['java']['oracle']['accept_oracle_download_terms'] = true
```

OS: Ubuntu 14.04

**Comment by rveznaver** [comment]
Hi @caussourd,
I couldn't reproduce your issue in the kitchen test for Ubuntu 14.04.
Which version of the Java cookbook are you using?
According to [the cookbook changelog](https://github.com/agileorbit-cookbooks/java/blob/master/CHANGELOG.md), version 1.36 onwards should automatically add the PPA repo for OpenJDK 8.

**Comment by caussourd** [comment]
@rveznaver You are right, my Java cookbook was at 1.35... Thanks!

**Comment by rveznaver** [comment]
You're welcome!

**Comment by jyotiruhil** [comment]
Hi, I am using version 1.4.0, and still getting the same error. 

`    * No candidate version available for openjdk-8-jdk
    ================================================================================
    Error executing action `install` on resource 'apt_package[openjdk-8-jdk]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No candidate version available for openjdk-8-jdk
`

**Comment by rveznaver** [comment]
Hi @jyotiruhil, I can't reproduce your issue. Have you tried asking at https://github.com/agileorbit-cookbooks/java?
