### ISSUE TITLE
on ubuntu 16.04, marathon uses the poise_service resource which results in upstart being configured rather than systemd

### ISSUE THREAD

**Issue by elijah** [mdsol/marathon_cookbook#45]
On ubuntu 16.04, marathon uses the poise_service resource which results in upstart being configured rather than systemd.

I've dug in far enough to figure out that Chef::Platform::ServiceHelpers from chef 12.8.1 gets used and returns hints about the system to poise_service -- but I don't understand the inversion of control pattern used in poise_service well enough to debug what is going on here.  It *looks like* systemd should be preferred over upstart, and be spun up / used -- but for some reason it is not.

@coderanger is probably the person to ask for help debugging.

**Comment by elijah** [comment]
I just discovered that I was deeply confused because I was looking at master, when your develop branch explicitly calls upstart and configures the service that way - or attempts to - with no conditionals and no branching logic for anything but upstart.  What's pulled down from supermarket is clearly the develop branch.

I... will be sending you some patches soon, probably.  ;-)

**Comment by elijah** [comment]
Patches submitted, and I did some basic cleanup to make things pass in travis-ci again.

Should write some more tests for code coverage sometime soon.  This cookbook could use 'em.

**Comment by rveznaver** [comment]
Hi @elijah,

The supermarket version is a release made from commit 92f63ec99d256ac5c1d5f9d1d15442b4ff80a98e. The develop branch is temporary, no releases are ever made from anything but master.
Please try using the master branch directly in your Berksfile. If that works, then the only issue is that the version on supermarket is behind the master branch.

Thanks.

**Comment by elijah** [comment]
got it.  Yeah, it was behind.

I re-pushed my changes from last week to current master - still need all of
those to get travis-ci to behave and to make this cookbook run on current
Ubuntu LTS.

best,

--e

**Comment by rveznaver** [comment]
Just tested with Ubuntu 16.04 with Chef 12.10.24 on the latest master branch, and there seems to be no issue whatsoever. Marathon gets configured with systemd.

```
Recipe: marathon::service
         * poise_service[marathon] action enable
           * execute[systemctl daemon-reload] action nothing (skipped due to action :nothing)
           * template[/etc/systemd/system/marathon.service] action create
             - create new file /etc/systemd/system/marathon.service
             - update content in file /etc/systemd/system/marathon.service from none to bd538b
             --- /etc/systemd/system/marathon.service	2016-06-07 10:49:52.439600454 +0000
             +++ /etc/systemd/system/.chef-marathon.service20160607-24958-1tv5f13	2016-06-07 10:49:52.439600454 +0000
             @@ -1 +1,15 @@
             +[Unit]
             +Description=marathon
             +
             +[Service]
             +Environment=
             +ExecStart=/opt/marathon/wrapper
             +ExecReload=/bin/kill -HUP $MAINPID
             +KillSignal=TERM
             +User=marathon
             +WorkingDirectory=/opt/marathon
             +Restart=on-failure
             +
             +[Install]
             +WantedBy=multi-user.target
             - change mode from '' to '0644'
             - change owner from '' to 'root'
             - change group from '' to 'root'
           * execute[systemctl daemon-reload] action run
             - execute systemctl daemon-reload
           * service[marathon] action enable
             - enable service service[marathon]
           * service[marathon] action start
             - start service service[marathon]
```

**Comment by rveznaver** [comment]
See answer in #47. Reopen if reproducible in a Kitchen test.
