### ISSUE TITLE
Supermarket version is old

### ISSUE THREAD

**Issue by diegows** [mdsol/marathon_cookbook#49]
Hi,
 I think the code in the supermarket is old. I've tried to use it and it doesn't work in CentOS 7. "poise-service" is missing there, it's trying to configure update.

I've configured Berksfile to use version from git and works fine.

Thanks!

**Comment by bai** [comment]
It would be so much more convenient not to have it sourced from git in Berksfile.

**Comment by rveznaver** [comment]
Very true. I'll try to find some time this or next week to update and prepare both the marathon and mesos cookbook for a new release.

**Comment by bai** [comment]
Friendly bump 👻

**Comment by rveznaver** [comment]
Thanks. Working on the mesos cookbook first: https://github.com/mdsol/mesos_cookbook/tree/mesos_1.0 :)

**Comment by avinashkolluru** [comment]
Friendly bump again :)

**Comment by rveznaver** [comment]
Tagged and prepared for supermarket release! Pinging @rayrod2030 and @mjcdiggity to release version **2.2.0** or give me permissions on supermarket :)

**Comment by rveznaver** [comment]
@diegows, @bai, and @avinashkolluru: Thanks for the friendly bump and motivation!

**Comment by rayrod2030** [comment]
@rveznaver Added you as collaborator on Supermarket!  Thanks.

**Comment by rveznaver** [comment]
Great, thanks! Released 2.2.0 to Supermarket and closing this issue.
